/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dsafinalproject2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;


public class landingpage extends javax.swing.JFrame {
    
    public landingpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        landingpage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        createbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        alreadyaccount = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spring N' Flow - Landing Page");
        setMinimumSize(new java.awt.Dimension(1322, 758));

        landingpage.setBackground(new java.awt.Color(255, 255, 255));
        landingpage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 204, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Good day our dear customer!");
        landingpage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 349, 246, -1));
        landingpage.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 401, 1, 18));

        createbutton.setBackground(new java.awt.Color(255, 153, 51));
        createbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createbutton.setForeground(new java.awt.Color(255, 255, 255));
        createbutton.setText("Create Account");
        createbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbuttonActionPerformed(evt);
            }
        });
        landingpage.add(createbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 472, 238, 69));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText(" Do you already have an account?");
        landingpage.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 624, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        landingpage.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 0, -1, -1));

        alreadyaccount.setBackground(new java.awt.Color(153, 153, 153));
        alreadyaccount.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        alreadyaccount.setText("Yes");
        alreadyaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alreadyaccountActionPerformed(evt);
            }
        });
        landingpage.add(alreadyaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 615, 72, -1));

        jTextField1.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        landingpage.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 379, 238, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsafinalproject2/Working Man Logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 300));
        jLabel1.setMinimumSize(new java.awt.Dimension(300, 300));
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 300));
        landingpage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 360, 290));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsafinalproject2/pxfuel.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        landingpage.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 660, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(landingpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(landingpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void alreadyaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alreadyaccountActionPerformed
    
        
        //If "Yes" button is clicked, it will show the Login page
        
        loginpage lp = new loginpage();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_alreadyaccountActionPerformed

    private void createbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbuttonActionPerformed

        
        //If "Create Account" button is clicked, it will show the Create Account page
        
        createaccpage cap = new createaccpage();
        cap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createbuttonActionPerformed


    
    
    
    
    public static void main(String args[]) {

               /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new landingpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alreadyaccount;
    public javax.swing.JButton createbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JPanel landingpage;
    // End of variables declaration//GEN-END:variables
}
