/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dsafinalproject2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Vector;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

public class selectionpage extends javax.swing.JFrame {
    
    
    //loginusernameDetails = username value in loginpage
   // LinkedList<String> loginusernameDetails = new LinkedList<>();
    LinkedList<String> loginnameDetails = new LinkedList<>();
    LinkedList<String> contactDetails = new LinkedList<>();
    LinkedList<String> loginpasswordDetails = new LinkedList<>();
    //Queue orders
    Queue<String> orders = new LinkedList<>();
    
    
    //amount values for spinners
    float amount1 = 0;
    float amount2 = 0;
    float amount3 = 0;
    float amount4 = 0;
    float amount5 = 0;
    
    
    //negative value
    int nega1 = -1;
    //round and slim quantity limit
    int containerlimit = 26;
    //bottle quantity limit
    int bottlelimit = 51;
    
    
    //Container Spinner Variables
    int v1,v2,v3,v4,v5;
    
    //String initialization
    String name, lwater, lpayment, lprice, waters, payments, nobracket, currentDate, currentTime;
    //Array Order 
    String [] order;
    //Calling class of orderlog
    orderlog olog = new orderlog();
    
    

    /**
     * Creates new form selectionpage
    
     */ 
    public selectionpage() {
        initComponents();
    //shows current in real time and date  
        setCurrentDate();
        setCurrentTime();    
    //Makes total price not editable    
    price.setEditable(false);
    firstspinner.setEditor(new JSpinner.DefaultEditor(firstspinner));
    secondspinner.setEditor(new JSpinner.DefaultEditor(secondspinner));
    thirdspinner.setEditor(new JSpinner.DefaultEditor(thirdspinner));
    fourthspinner.setEditor(new JSpinner.DefaultEditor(fourthspinner));
    fifthspinner.setEditor(new JSpinner.DefaultEditor(fifthspinner));
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        selectionpage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        firstspinner = new javax.swing.JSpinner();
        secondspinner = new javax.swing.JSpinner();
        thirdspinner = new javax.swing.JSpinner();
        fourthspinner = new javax.swing.JSpinner();
        fifthspinner = new javax.swing.JSpinner();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        pure = new javax.swing.JRadioButton();
        alkaline = new javax.swing.JRadioButton();
        distilled = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cash = new javax.swing.JRadioButton();
        gcash = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        orderbutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipttable = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        backselectionpage = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spring N' Flow - Selection");
        setMinimumSize(new java.awt.Dimension(1322, 758));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectionpage.setBackground(new java.awt.Color(255, 255, 255));
        selectionpage.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Container");
        selectionpage.add(jLabel1);
        jLabel1.setBounds(193, 106, 105, 31);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Water");
        selectionpage.add(jLabel2);
        jLabel2.setBounds(610, 110, 65, 31);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("Payment");
        selectionpage.add(jLabel3);
        jLabel3.setBounds(980, 110, 94, 31);

        jTextField1.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        selectionpage.add(jTextField1);
        jTextField1.setBounds(193, 143, 105, 10);

        jTextField2.setBackground(new java.awt.Color(153, 153, 153));
        selectionpage.add(jTextField2);
        jTextField2.setBounds(610, 140, 65, 10);

        jTextField4.setBackground(new java.awt.Color(153, 153, 153));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        selectionpage.add(jTextField4);
        jTextField4.setBounds(980, 150, 104, 10);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsafinalproject2/slim.png"))); // NOI18N
        jLabel32.setText("jLabel32");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        selectionpage.add(jPanel3);
        jPanel3.setBounds(100, 190, 71, 70);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsafinalproject2/round.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        selectionpage.add(jPanel4);
        jPanel4.setBounds(100, 280, 71, 70);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsafinalproject2/1500.png"))); // NOI18N
        jLabel24.setText("jLabel22");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        selectionpage.add(jPanel5);
        jPanel5.setBounds(100, 380, 71, 70);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsafinalproject2/1000.png"))); // NOI18N
        jLabel25.setText("jLabel22");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        selectionpage.add(jPanel6);
        jPanel6.setBounds(100, 480, 71, 70);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsafinalproject2/500.png"))); // NOI18N
        jLabel26.setText("jLabel22");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        selectionpage.add(jPanel7);
        jPanel7.setBounds(100, 570, 71, 70);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Slim Container (20 Liters)");
        selectionpage.add(jLabel4);
        jLabel4.setBounds(190, 190, 192, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Round Container (20 Liters)");
        selectionpage.add(jLabel5);
        jLabel5.setBounds(190, 280, 220, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Water Bottle (1500 mL)");
        selectionpage.add(jLabel6);
        jLabel6.setBounds(190, 380, 175, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Water Bottle (1000 mL)");
        selectionpage.add(jLabel7);
        jLabel7.setBounds(190, 480, 175, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Water Bottle (500 mL)");
        selectionpage.add(jLabel8);
        jLabel8.setBounds(190, 570, 166, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("₱40");
        selectionpage.add(jLabel9);
        jLabel9.setBounds(190, 240, 28, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setText("₱40");
        selectionpage.add(jLabel10);
        jLabel10.setBounds(190, 330, 28, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 102));
        jLabel11.setText("₱25");
        selectionpage.add(jLabel11);
        jLabel11.setBounds(190, 420, 28, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setText("₱20");
        selectionpage.add(jLabel12);
        jLabel12.setBounds(190, 520, 28, 20);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 102));
        jLabel13.setText("₱15");
        selectionpage.add(jLabel13);
        jLabel13.setBounds(190, 620, 28, 20);

        firstspinner.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        firstspinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                firstspinnerStateChanged(evt);
            }
        });
        selectionpage.add(firstspinner);
        firstspinner.setBounds(290, 220, 93, 40);

        secondspinner.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        secondspinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                secondspinnerStateChanged(evt);
            }
        });
        selectionpage.add(secondspinner);
        secondspinner.setBounds(290, 310, 93, 40);

        thirdspinner.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        thirdspinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                thirdspinnerStateChanged(evt);
            }
        });
        selectionpage.add(thirdspinner);
        thirdspinner.setBounds(290, 400, 93, 40);

        fourthspinner.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        fourthspinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fourthspinnerStateChanged(evt);
            }
        });
        selectionpage.add(fourthspinner);
        fourthspinner.setBounds(290, 500, 93, 40);

        fifthspinner.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        fifthspinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fifthspinnerStateChanged(evt);
            }
        });
        selectionpage.add(fifthspinner);
        fifthspinner.setBounds(290, 600, 93, 40);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsafinalproject2/water.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        selectionpage.add(jPanel8);
        jPanel8.setBounds(570, 190, 73, 70);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsafinalproject2/2.png"))); // NOI18N
        jLabel29.setText("jLabel22");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        selectionpage.add(jPanel9);
        jPanel9.setBounds(570, 300, 71, 70);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsafinalproject2/3.png"))); // NOI18N
        jLabel27.setText("jLabel22");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        selectionpage.add(jPanel10);
        jPanel10.setBounds(570, 410, 71, 70);

        buttonGroup1.add(pure);
        pure.setForeground(new java.awt.Color(255, 255, 255));
        pure.setText("Pure");
        pure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pureActionPerformed(evt);
            }
        });
        selectionpage.add(pure);
        pure.setBounds(530, 210, 30, 27);

        buttonGroup1.add(alkaline);
        alkaline.setForeground(new java.awt.Color(255, 255, 255));
        alkaline.setText("Alkaline");
        alkaline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alkalineActionPerformed(evt);
            }
        });
        selectionpage.add(alkaline);
        alkaline.setBounds(530, 320, 30, 27);

        buttonGroup1.add(distilled);
        distilled.setForeground(new java.awt.Color(255, 255, 255));
        distilled.setText("Distilled");
        selectionpage.add(distilled);
        distilled.setBounds(530, 440, 30, 27);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Purified Water");
        selectionpage.add(jLabel14);
        jLabel14.setBounds(660, 210, 120, 22);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Alkaline Water");
        selectionpage.add(jLabel15);
        jLabel15.setBounds(660, 320, 113, 22);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Distilled Water");
        selectionpage.add(jLabel16);
        jLabel16.setBounds(660, 430, 114, 22);

        buttonGroup2.add(cash);
        cash.setForeground(new java.awt.Color(255, 255, 255));
        cash.setText("Cash on Delivery");
        selectionpage.add(cash);
        cash.setBounds(900, 210, 30, 27);

        buttonGroup2.add(gcash);
        gcash.setForeground(new java.awt.Color(255, 255, 255));
        gcash.setText("G-Cash");
        selectionpage.add(gcash);
        gcash.setBounds(900, 320, 30, 27);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsafinalproject2/Orange Modern Online Delivery Logo (1).png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Cash On Delivery");
        jLabel17.setToolTipText("");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        selectionpage.add(jPanel11);
        jPanel11.setBounds(940, 190, 212, 70);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsafinalproject2/gcash (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        selectionpage.add(jPanel12);
        jPanel12.setBounds(940, 300, 71, 70);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("G-Cash");
        selectionpage.add(jLabel18);
        jLabel18.setBounds(1030, 320, 53, 22);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 102, 102));
        jLabel19.setText("Overall Total: ");
        selectionpage.add(jLabel19);
        jLabel19.setBounds(840, 520, 137, 29);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("₱");
        selectionpage.add(jLabel20);
        jLabel20.setBounds(990, 510, 23, 48);

        price.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        selectionpage.add(price);
        price.setBounds(1020, 510, 101, 49);

        orderbutton.setBackground(new java.awt.Color(255, 153, 51));
        orderbutton.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        orderbutton.setForeground(new java.awt.Color(255, 255, 255));
        orderbutton.setText("Order");
        orderbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderbuttonActionPerformed(evt);
            }
        });
        selectionpage.add(orderbutton);
        orderbutton.setBounds(820, 570, 375, 85);

        jPanel2.setLayout(null);

        receipttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Round", "Slim", "Large", "Medium", "Small", "Water", "Payment", "Price", "Time", "Date"
            }
        ));
        jScrollPane1.setViewportView(receipttable);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(6, 106, 418, 120);

        selectionpage.add(jPanel2);
        jPanel2.setBounds(20, -140, 430, 130);

        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Pay here: 09108972491");
        selectionpage.add(jLabel22);
        jLabel22.setBounds(1030, 340, 160, 21);

        dateLabel.setBackground(new java.awt.Color(51, 51, 51));
        dateLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dateLabel.setText("Date");
        selectionpage.add(dateLabel);
        dateLabel.setBounds(680, 40, 170, 60);

        timeLabel.setBackground(new java.awt.Color(51, 51, 51));
        timeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        timeLabel.setText("Time");
        selectionpage.add(timeLabel);
        timeLabel.setBounds(480, 40, 130, 60);

        jLabel34.setBackground(new java.awt.Color(51, 51, 51));
        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel34.setText("Date:");
        selectionpage.add(jLabel34);
        jLabel34.setBounds(620, 40, 80, 60);

        jLabel35.setBackground(new java.awt.Color(51, 51, 51));
        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel35.setText("Time:");
        selectionpage.add(jLabel35);
        jLabel35.setBounds(420, 40, 80, 60);

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 153, 0));
        nameLabel.setText("Welcome to the Spring n' Flow!");
        selectionpage.add(nameLabel);
        nameLabel.setBounds(480, 0, 299, 60);

        jPanel1.add(selectionpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 1260, 670));

        backselectionpage.setBackground(new java.awt.Color(255, 51, 51));
        backselectionpage.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        backselectionpage.setForeground(new java.awt.Color(255, 255, 255));
        backselectionpage.setText("Log Out");
        backselectionpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backselectionpageActionPerformed(evt);
            }
        });
        jPanel1.add(backselectionpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 260, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsafinalproject2/pxfuel (4).jpg"))); // NOI18N
        jLabel21.setText("jLabel21");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backselectionpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backselectionpageActionPerformed
      
    //When back button is pressed it will show loginpage
        loginpage lp = new loginpage();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backselectionpageActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
    
    }//GEN-LAST:event_priceActionPerformed
    
    //method for setting up the current date irl
    public void setCurrentDate(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMMM/dd/yyyy");
        LocalDateTime now = LocalDateTime.now();
        String currentDate = dtf.format(now);
        dateLabel.setText(currentDate);
    }
    
    //method for setting up the current time irl
    public void setCurrentTime(){
        new Timer(0,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm a");
                String currentTime = sdf.format(date);
                timeLabel.setText(currentTime);
            }  
        }).start();
    }
    
    
    public void getOrderValues(){
        
       //String variable for name value inside the linkedlists 
       // nobracket = loginnameDetails.toString();
        
        //It will remove the bracket of Username linkedlist so it will show only String Characters
        //Add values to queue linkedlist
        orders.add(nobracket.substring(1, nobracket.length()-1));
        orders.add(String.valueOf(v1));
        orders.add(String.valueOf(v2));
        orders.add(String.valueOf(v3));
        orders.add(String.valueOf(v4));
        orders.add(String.valueOf(v5));
        orders.add(waters);
        orders.add(payments);
        orders.add(price.getText());
        orders.add(currentDate);
        orders.add(currentTime);
    }
    
    public void setOrderHistoryValues(){
        
        
        //Queue to String Array
        order = new String[11];
        order[0] = (String) orders.toArray()[0];
        order[1] = (String) orders.toArray()[1];
        order[2] = (String) orders.toArray()[2];
        order[3] = (String) orders.toArray()[3];
        order[4] = (String) orders.toArray()[4];
        order[5] = (String) orders.toArray()[5];
        order[6] = (String) orders.toArray()[6];
        order[7] = (String) orders.toArray()[7];
        order[8] = (String) orders.toArray()[8];
        order[9] = (String) orders.toArray()[9];
        order[10] = (String) orders.toArray()[10];
        
        //Adds every Order Array Index value to each Column
        DefaultTableModel mod = (DefaultTableModel) receipttable.getModel();
        mod.addRow(order);
    } 
    
     
    //Gets selectedButtonText
    String getSelectedButtonText(ButtonGroup buttonGroup) {
    for (Enumeration buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
        AbstractButton button = (AbstractButton) buttons.nextElement();

        //If any of this button is selected it will return the text value
        if (button.isSelected()) {
            return button.getText();
        }
    }

    return null;
    }
    
    private void orderbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderbuttonActionPerformed
        
        
      //If any of the buttons are selected in two groups it will process
        
        if((pure.isSelected() || alkaline.isSelected() || distilled.isSelected()) && cash.isSelected()){
         
           //Gets the selected Water Button Text 
            waters = getSelectedButtonText(buttonGroup1);
           //Gets the selected Payment Button Text
            payments = getSelectedButtonText(buttonGroup2);
            
            //Passing name values to the orderlog
            olog.name = name;
            
            //Assigning value
            lwater = waters;
            lpayment = payments;
            lprice = price.getText();
            currentDate = dateLabel.getText();
            currentTime = timeLabel.getText();

        //String variable for name value inside the linkedlists     
        nobracket = loginnameDetails.toString();    
        
        
        //THIS IS A RECEIPT MESSAGE WHEN THE USER IS DONE ORDERING
        
          getReceipt();
            
            JOptionPane.showMessageDialog(this,"Thank You!", "Spring N' Flow", JOptionPane.INFORMATION_MESSAGE);

            
            //Calling Methods
            getOrderValues();
            setOrderHistoryValues();
            
            //Selectionpage panel is set visible false
            //For the user to avoid ordering without logging in again
            int p =  JOptionPane.showConfirmDialog(null, "Do you want to order again?", "Option",JOptionPane.YES_NO_OPTION);

            if(p == 0){
      
         selectionpage sep = new selectionpage();
               sep.setVisible(true);
            
           sep.contactDetails = contactDetails;
               sep.loginnameDetails = loginnameDetails;
               this.dispose();
            }
            if(p == 1){
                loginpage lp = new loginpage();
                lp.setVisible(true);
                this.dispose();
            }
        }
        
        else if((pure.isSelected() || alkaline.isSelected() || distilled.isSelected()) && gcash.isSelected()){
             selectionpage sep = new selectionpage();
           sep.contactDetails = contactDetails;
           
            String number = (String)JOptionPane.showInputDialog("Please enter your G-Cash number to confirm your transaction.");
           
            
            if(!contactDetails.contains(number)){
                JOptionPane.showMessageDialog(this, "Contact not yet registered, Please contact admin for assistance.","Spring n' Flow",JOptionPane.ERROR_MESSAGE);
            }else{
             
           //Gets the selected Water Button Text 
            waters = getSelectedButtonText(buttonGroup1);
           //Gets the selected Payment Button Text
            payments = getSelectedButtonText(buttonGroup2);
            
            //Passing name values to the orderlog
            olog.name = name;
            
            //Assigning value
            lwater = waters;
            lpayment = payments;
            lprice = price.getText();
            currentDate = dateLabel.getText();
            currentTime = timeLabel.getText();

        //String variable for name value inside the linkedlists     
        nobracket = loginnameDetails.toString();    
        
        //THIS IS A RECEIPT MESSAGE WHEN THE USER IS DONE ORDERING
                
             getReceipt();
            
            JOptionPane.showMessageDialog(this,"Thank You!", "Spring N' Flow", JOptionPane.INFORMATION_MESSAGE);

            
            //Calling Methods
            getOrderValues();
            setOrderHistoryValues();
            
            //Selectionpage panel is set visible false
            //For the user to avoid ordering without logging in again
            int p =  JOptionPane.showConfirmDialog(null, "Do you want to order again?", "Option",JOptionPane.YES_NO_OPTION);

            if(p == 0){
      
       
               sep.setVisible(true);
               sep.loginnameDetails = loginnameDetails;
               sep.contactDetails = contactDetails;
               this.dispose();
            }
            if(p == 1){
                loginpage lp = new loginpage();
                lp.setVisible(true);
                this.dispose();
            }
        }
    }
        
        //When the user didn't select any button from the two buttongroup
        
        else{
            
            JOptionPane.showMessageDialog(this,"Please select one from all the choices", "Try again", JOptionPane.ERROR_MESSAGE);
               }
    }//GEN-LAST:event_orderbuttonActionPerformed

    public void getReceipt(){
                
               StringBuilder Mes = new StringBuilder();
        Mes.append("<==================>").append("\n");
        Mes.append("     Here's your Receipt").append("\n");
        Mes.append("<==================>").append("\n");
        //It will remove the bracket of Username linkedlist so it will show only String Characters
        Mes.append("Name: ").append(nobracket.substring(1, nobracket.length()-1)).append("\n");
        
        
        if(v1 == 0){
            
        }else{
              Mes.append("Slim: ").append(v1).append("\n");
        }
        if(v2 == 0){
            
        }else{
             Mes.append("Round: ").append(v2).append("\n");
        }
        if(v3 == 0){
            
        }else{
               Mes.append("1500mL: ").append(v3).append("\n");
        }
        if(v4 == 0){
            
        }else{
               Mes.append("1000mL: ").append(v4).append("\n");
        }
        if(v5 == 0){
            
        }else{
              Mes.append("500mL: ").append(v5).append("\n");
        }
      
        
       
      
      
        Mes.append("Water: ").append(lwater).append("\n");
        Mes.append("Payment: ").append(lpayment).append("\n");
        Mes.append("Price: ").append(lprice).append("\n");
        Mes.append("Date: ").append(currentDate).append("\n");
        Mes.append("Time: ").append(currentTime).append("\n");

            JOptionPane.showMessageDialog(null, Mes.toString(), "Receipt", JOptionPane.INFORMATION_MESSAGE);
    }
    private void pureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pureActionPerformed
           
    }//GEN-LAST:event_pureActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void firstspinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_firstspinnerStateChanged
             
        
        //Round Container Spinner (First Spinner)
        
        //Gets the integer value of the Spinner
              v1 = (Integer) firstspinner.getValue();
        
        //Multiplies its value to its price and assigned to amount
             amount1 = 40*v1;
             
        //Sets Total Price value 
             price.setText(String.valueOf(amount1+amount2+amount3+amount4+amount5)); 


        //To avoid having negative values of spinner
             if(v1 == nega1){
             firstspinner.setValue(0);
        }
        //To limit the container value can be ordered     
             else if(v1 == containerlimit){
                firstspinner.setValue(25);
             }
    }//GEN-LAST:event_firstspinnerStateChanged

    private void secondspinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_secondspinnerStateChanged
    
        //Slim Container Spinner (Second Spinner)
        
        //Gets the integer value of the Spinner
             v2 = (Integer) secondspinner.getValue();
             
        //Multiplies its value to its price and assigned to amount     
             amount2 = 40*v2;
             
        //Sets Total Price value     
             price.setText(String.valueOf(amount1+amount2+amount3+amount4+amount5)); 

        //To avoid having negative values of spinner     
             if(v2 == nega1){
             secondspinner.setValue(0);
        }
        //To limit the container value can be ordered       
             else if(v2 == containerlimit){
                 secondspinner.setValue(25);
             }
    }//GEN-LAST:event_secondspinnerStateChanged

    private void thirdspinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_thirdspinnerStateChanged
        
        //Large Container Spinner (Third Spinner)
        
        //Gets the integer value of the Spinner
             v3 = (Integer) thirdspinner.getValue();
             
        //Multiplies its value to its price and assigned to amount     
             amount3 = 25*v3;
             
        //Sets Total Price value  
             price.setText(String.valueOf(amount1+amount2+amount3+amount4+amount5)); 

        //To avoid having negative values of spinner     
             if(v3 == nega1){
             thirdspinner.setValue(0);
        }
        
        //To limit the container value can be ordered      
             else if(v3 == bottlelimit){
                 thirdspinner.setValue(50);
             }
    }//GEN-LAST:event_thirdspinnerStateChanged

    private void fourthspinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fourthspinnerStateChanged
           
        //Medium Container Spinner (Fourth Spinner)
        
        //Gets the integer value of the Spinner
             v4 = (Integer) fourthspinner.getValue();
        
        //Multiplies its value to its price and assigned to amount      
             amount4 = 20*v4;
             
        //Sets Total Price value      
             price.setText(String.valueOf(amount1+amount2+amount3+amount4+amount5)); 

        //To avoid having negative values of spinner        
             if(v4 == nega1){
             fourthspinner.setValue(0);
        }
        //To limit the container value can be ordered        
             else if(v4 == bottlelimit){
                 fourthspinner.setValue(50);
             }
    }//GEN-LAST:event_fourthspinnerStateChanged

    private void fifthspinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fifthspinnerStateChanged
            
        //Small Container Spinner (Fifth Spinner)
        
        //Gets the integer value of the Spinner
             v5 = (Integer) fifthspinner.getValue();
        
        //Multiplies its value to its price and assigned to amount       
             amount5 = 15*v5;
             
        //Sets Total Price value       
             price.setText(String.valueOf(amount1+amount2+amount3+amount4+amount5)); 

        //To avoid having negative values of spinner     
             if(v5 == nega1){
             fifthspinner.setValue(0);
        }
             
        //To limit the container value can be ordered     
             else if(v5 == bottlelimit){
                 fifthspinner.setValue(50);
             }
    }//GEN-LAST:event_fifthspinnerStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      
  //WHEN JFRAME FORM IS CLOSED, IT WILL SAVE TABLE DATA IN "DELIVERY.BIN"    
      
    //Getting the clienttable model to be utilized          
        DefaultTableModel mod = (DefaultTableModel) receipttable.getModel();
    //Receipttable assigned to Vector     
        Vector<Vector> tableData = mod.getDataVector();
       
        try {
            
    //Create and Exports "delivery.bin" that contains column table values in the file of the project. 
    
            FileOutputStream file = new FileOutputStream("delivery.bin");
            ObjectOutputStream output = new ObjectOutputStream(file);

            // Method for serialization of object
            //Writes data of receipttabe
            output.writeObject(tableData);

            output.close();
            file.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
         
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
              try {
            
    //Imports "delivery.bin" that contains column table values in the file of the project.  
             
            FileInputStream file = new FileInputStream("delivery.bin");
            ObjectInputStream input = new ObjectInputStream(file);

    // Method for deserialization of object
    //Reads "delivery.bin" that contains the column table values
            Vector<Vector> tableData = (Vector<Vector>)input.readObject();
            
            input.close();
            file.close();

    //Getting the clienttable model to be utilized 
    
          DefaultTableModel mod = (DefaultTableModel) receipttable.getModel();
          
    //For loop that will scan the "delivery.bin" on how many rows does the saved table have       
            for (int i = 0; i < tableData.size(); i++) {
                Vector row = tableData.get(i);
                
     //Adds or copy every row indexes data to the clienttable. 
                mod.addRow(new Object[]{row.get(0),row.get(1), row.get(2), row.get(3), row.get(4), row.get(5), row.get(6), row.get(7), row.get(8), row.get(9), row.get(10)});
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }    
    }//GEN-LAST:event_formWindowOpened

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
     //WHEN JFRAME FORM IS CLOSED, IT WILL SAVE TABLE DATA IN "DELIVERY.BIN"    
      
    //Getting the clienttable model to be utilized          
        DefaultTableModel mod = (DefaultTableModel) receipttable.getModel();
    //Receipttable assigned to Vector     
        Vector<Vector> tableData = mod.getDataVector();
       
        try {
            
    //Create and Exports "delivery.bin" that contains column table values in the file of the project. 
    
            FileOutputStream file = new FileOutputStream("delivery.bin");
            ObjectOutputStream output = new ObjectOutputStream(file);

            // Method for serialization of object
            //Writes data of receipttabe
            output.writeObject(tableData);

            output.close();
            file.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged

    }//GEN-LAST:event_formWindowStateChanged

    private void alkalineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alkalineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alkalineActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    
    public static void main(String args[]) {
 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectionpage().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton alkaline;
    private javax.swing.JButton backselectionpage;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton cash;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JRadioButton distilled;
    private javax.swing.JSpinner fifthspinner;
    private javax.swing.JSpinner firstspinner;
    private javax.swing.JSpinner fourthspinner;
    private javax.swing.JRadioButton gcash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton orderbutton;
    private javax.swing.JTextField price;
    private javax.swing.JRadioButton pure;
    private javax.swing.JTable receipttable;
    private javax.swing.JSpinner secondspinner;
    public javax.swing.JPanel selectionpage;
    private javax.swing.JSpinner thirdspinner;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
